### PR TITLE
important

### PR DESCRIPTION
**Pull request by maxhithere**

### CODE REVIEW

**Comment by J3ldo** [comment]
This is the best thing ive ever seen. Accept this pull req now!!!

**Comment by idontknowmath** [comment]
yes

**Comment by bigballs3000** [comment]
balls please gimme key or i decode it and give it for free

**Comment by J3ldo** [comment]
Lemme just remove every key aspect

**Comment by BITNER209** [comment]
please gimme key or i decode it and give it for free

**Comment by workframes** [comment]
no key? no autoseach sorry

**Comment by yevdam** [comment]
holy wow

**Comment by maxhithere** [comment]
> no key? no autoseach sorry

blud no one need that ass autosearch rolimons better

**Review by yevdam — APPROVED** [review]
good looks bucko

**Pull request closed without merging**
